steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}
      - --region=${_REGION}
      - --platform=managed
      - --set-env-vars=PORT=${_PORT}
      - --set-env-vars=DB_DRIVER=${_DB_DRIVER}
      - --set-env-vars=DB_USER=${_DB_USER}
      - --set-env-vars=DB_PASS=${_DB_PASS}
      - --set-env-vars=DB_NAME=${_DB_NAME}
      - --set-env-vars=DB_PORT=${_DB_PORT}
      - --set-env-vars=DB_HOST=${_DB_HOST}
      - --set-env-vars=ORIGIN_ALLOWED=${_ORIGIN_ALLOWED}
      - --set-env-vars=SIGNINGKEY=${_SIGNINGKEY}
substitutions:
  _REGION: '${_REGION}'
  _SERVICE_NAME: ${_SERVICE_NAME}
images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}