version:  '3'
services:
  app:
    build:  
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/go/src/task_checker
    networks:
      - task-checker
    ports:
      - 8080:8080
    networks:
      - task-checker
    environment:
      - ENV=development

  postgresql:
    image: postgres:12.4
    container_name: psql
    ports:
      - 5555:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
    hostname: postgres
    restart: always
    user: root
    networks:
      - task-checker