FROM golang:1.14.12

WORKDIR /go/src

COPY go.mod go.sum ./
RUN go mod download

COPY ./src ./src
RUN go generate ./src


RUN go get -v golang.org/x/tools/gopls 
RUN go get -v github.com/go-delve/delve/cmd/dlv
ENV PORT=8080
